### PR TITLE
Add innerStrokeColor property

### PR DESCRIPTION
**Pull request by shkutkov**
It would be great to have ability change stroke color for inner border. 

For example we can change innerStrokeColor to clear color to get such result:

### CODE REVIEW

**Comment by nicolaschengdev** [comment]
Hi shkutkov,

nice idea.

I have to rename `strokeColor` to `outerStrokeColor` for this. 

~~In your case, the `wantsDefaultContentAppearance` property could also be used.~~

**Nicolas**

**Comment by shkutkov** [comment]
Changing strokeColor to outerStorkeColor might brake someone's code... 

Could you please explain in more details how wantsDefaultContentAppearance property could be used in my case? Thanks!

**Comment by nicolaschengdev** [comment]
The `strokeColor` property will be kept (but DEPRECATED) in next release.

Sorry, the `wantsDefaultContentAppearance` cannot be used in order to clear the inner stroke.

This property is used when you want to keep the default appearance of the content view controller passed to _WYPopoverController_.

If `wantsDefaultContentAppearance` is equals to YES then
- `innerCornerRadius` is automatically equals to 0
- `UINavigationBar` view appearance is not altered when your content view controller is type of `UINavigationController` class

Thanks for your contribution!

**Nicolas**

**Comment by shkutkov** [comment]
Thanks for the explanation and for your work on WYPopoverController!

**Pull request merged**
