### PR TITLE
Nil check

### PR DESCRIPTION
**Pull request by hsoi**
Issue #64 wasn't fully resolved. Need to check for valid object before dereferencing because dereferencing nil is bad.

### CODE REVIEW

**Comment by nicolaschengdev** [comment]
Hi hsoi,

there is something I don't understand :
In which case, popover itself would be nil during animation ?
Each popover must be retained by the developer until the end of its use.

Nicolas

**Comment by hsoi** [comment]
It didn't always happen, but in my app if we did something like tap to show, tap to dismiss, then tap to show again, tap to dismiss again... and then it would crash because various blocks were attempting to dereference nil. So, not the first time, but crash the second time.

It may be unique to my app. I do maintain a strong reference to the popover, but sometimes I do have to nil out the reference depending what's going on so there's no chance of a dangling or stale reference or the popover lingering on screen when we don't want it.

Nevertheless, the guards aren't harmful and are good defense.

Conversely, instead of the direct data member access, why not go through (property) accessors? That would eliminate the dereferencing entirely (which is legal but isn't common in Objective-C), and should also work around this since messaging nil objects is safe and legal.

**Comment by nicolaschengdev** [comment]
Thanks for the explanation.

**Comment by hsoi** [comment]
You're welcome. Thank you for your responsiveness.

**Pull request merged**
